<?php
/**
 * Implements hook_block_info.
 */
function iit_display_hours_block_info() {
  $blocks['hours'] = array(
    'info' => t('IIT Display Library Hours'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}

//Communications & Marketing format for times
function iit_display_hours_format_time ($time){ 
	$time = str_replace(':00','',$time);
	$time = str_replace('am','a.m.',$time);
	$time = str_replace('pm','p.m.',$time);
	return $time;
}


function iit_display_hours_get_and_format_todays_date_time(){
  $dateFormat="l, F j";
  $timeFormat="g:ia";
  $today = date($dateFormat).", " . iit_display_hours_format_time(date($timeFormat));
  return $today;
}


function iit_display_hours_format_message(){

  $today=iit_display_hours_get_and_format_todays_date_time();
  return $today;
  
}

function iit_display_hours_block_view($delta = '') {
  $block['subject'] = t("Today's Hours");
  $block['content'] = t('@display_msg',array(
    '@display_msg' => iit_display_hours_format_message()
  ));
  return $block;
}

// http://www.wdtutorials.com/drupal-7/drupal-7-how-to-create-module-part-1#.VV47xvlVhBc
// https://ezproxy.gl.iit.edu/login?url=http://dx.doi.org/10.1007/978-1-4302-2839-4