<?php

  $GLOBALS['conf']['cache'] = FALSE;
/**
 * Implements hook_block_info.
 */
 
function iit_display_hours_block_info() {
  $blocks['hours'] = array(
    'info' => t('IIT Display Library Hours'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}
function iit_display_hours_block_view($delta = '') {
  $incluldeOpenMsg=1;
  $msg = "<p>" . iit_display_hours_get_and_format_todays_date() . "</p>";
  $msg .= iit_display_hours_format_message($incluldeOpenMsg);
  $block['subject'] = t("Today's Hours");
  $block['content'] = $msg;
  return $block;
}
 //Include shared functions.
module_load_include('inc', 'libraries', 'hours_functions');


// http://www.wdtutorials.com/drupal-7/drupal-7-how-to-create-module-part-1#.VV47xvlVhBc
// https://ezproxy.gl.iit.edu/login?url=http://dx.doi.org/10.1007/978-1-4302-2839-4
